apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: asphones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: amandevops8080/asphones-backend:latest
          ports:
            - containerPort: 7071
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: aman
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: backend-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: asphones
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 7071
      targetPort: 7071
      protocol: TCP
      nodePort: 31100