apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: asphones
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: amandevops8080/backend-asphones
          imagePullSecrets:
            - name: regcred
          ports:
            - containerPort: 7071
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DB_HOST
              value: database-1.c50eqi0c2eg3.ap-south-1.rds.amazonaws.com
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: aman
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: asphones
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 7071
      targetPort: 7071
      protocol: TCP
      nodePort: 31100