apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: asphones
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      name: frontend
    spec:
      containers:
        - name: frontend
          image: amandevops8080/frontend-asphones
          imagePullSecrets:
            - name: regcred
          ports:
            - containerPort: 80
      
          env:
             - name: VITE_BACKEND_URL
               value: "http://54.173.255.161:31100"
          

          volumeMounts:
            - name: nginx-cache
              mountPath: /usr/share/nginx/html
            - name: nginx-cache
              mountPath: /var/cache/nginx
      volumes:
        - name: nginx-cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: asphones
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 8888
      protocol: TCP
      nodePort: 32000
