apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: asphones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: amandevops8080/frontend-asphones:latest
          imagePullSecrets:
            - name: regcred
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: frontend-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: asphones
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 32000
