@Library('Shared') _
pipeline {
    agent any

    stages {
        stage("Workspace cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }

        stage('Git: Code Checkout') {
            steps {
                script {
                    code_checkout("https://github.com/aman-3701/ASPhones.git", "master")
                }
            }
        }

        stage("Git: Code update and push to GitHub") {
            steps {
                script {
                    // withCredentials([gitUsernamePassword(credentialsId: 'git_cred', gitToolName: 'Default')]) {
                        // sh '''

                       withCredentials([usernamePassword(credentialsId: 'git_cred', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
                sh '''
                    echo "Cloning the repo..."
                    git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/aman-3701/ASPhones.git

                    cd ASPhones

                    echo "Checking repository status: "
                    git status

                    git config user.name "aman-3701"
                    git config user.email "ry1185449@gmail.com"

                    echo "Adding changes to git: "
                    git add .

                    if git diff --cached --quiet; then
                        echo "No changes to commit, creating dummy commit"
                        git commit --allow-empty -m "Trigger build or force push"
                    else
                        echo "Committing changes"
                        git commit -m "Updated environment variables"
                    fi

                    echo "Pushing changes to GitHub: "
                    git push origin master
                '''
                    }
                 }
            }
        }
    }
    post {
        success {
            script {
                emailext attachLog: true,
                    from: 'ry1185449@gmail.com',
                    subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
                    body: """
                        <html>
                        <body>
                            <div style=\"background-color: #FFA07A; padding: 10px; margin-bottom: 10px;\">
                                <p style=\"color: black; font-weight: bold;\">Project: ${env.JOB_NAME}</p>
                            </div>
                            <div style=\"background-color: #90EE90; padding: 10px; margin-bottom: 10px;\">
                                <p style=\"color: black; font-weight: bold;\">Build Number: ${env.BUILD_NUMBER}</p>
                            </div>
                            <div style=\"background-color: #87CEEB; padding: 10px; margin-bottom: 10px;\">
                                <p style=\"color: black; font-weight: bold;\">URL: ${env.BUILD_URL}</p>
                            </div>
                        </body>
                        </html>
                """,
                to: 'sumitaws761@gmail.com',
                mimeType: 'text/html'
            }
        }
        failure {
            script {
                emailext attachLog: true,
                    from: 'ry1185449@gmail.com',
                    subject: "Wanderlust Application build failed - '${currentBuild.result}'",
                    body: """
                        <html>
                        <body>
                            <div style=\"background-color: #FFA07A; padding: 10px; margin-bottom: 10px;\">
                                <p style=\"color: black; font-weight: bold;\">Project: ${env.JOB_NAME}</p>
                            </div>
                            <div style=\"background-color: #90EE90; padding: 10px; margin-bottom: 10px;\">
                                <p style=\"color: black; font-weight: bold;\">Build Number: ${env.BUILD_NUMBER}</p>
                            </div>
                        </body>
                        </html>
                """,
                to: 'sumitaws761@gmail.com',
                mimeType: 'text/html'
            }
        }
    }
}